sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t react-test -f ./client/Dockerfile.dev ./client
  
script:
  - docker run -e CI=true react-test npm test

after_success:
  - docker build -t gantihk/multi-client ./client
  - docker build -t gantihk/multi-server ./server
  - docker build -t gantihk/multi-nginx ./nginx
  - docker build -t gantihk/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push gantihk/multi-client
  - docker push gantihk/multi-server
  - docker push gantihk/multi-nginx
  - docker push gantihk/multi-worker

  deploy:
    edge: true
    provider: elasticbeanstalk
    region: us-east-2
    app: multi-docker
    env: MultiDocker-env-1
    bucket_name: elasticbeanstalk-us-east-2-848819479142
    bucket_path: docker-multi
    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY